environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      LLVM_VERSION: 7.0.0
      LLVM_VERSION_SHORT: 70
      VS_MAJOR_VERSION: 14 
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      LLVM_VERSION: 7.0.0
      LLVM_VERSION_SHORT: 70
      VS_MAJOR_VERSION: 14 
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      LLVM_VERSION: 7.0.0
      LLVM_VERSION_SHORT: 70
      VS_MAJOR_VERSION: 14
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      LLVM_VERSION: 6.0.1
      LLVM_VERSION_SHORT: 60
      VS_MAJOR_VERSION: 14
      USE_CUDA: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      LLVM_VERSION: 6.0.1
      LLVM_VERSION_SHORT: 60
      VS_MAJOR_VERSION: 14
      USE_CUDA: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      LLVM_VERSION: 5.0.2
      LLVM_VERSION_SHORT: 50
      VS_MAJOR_VERSION: 14

install:
  - if /I "%LLVM_VERSION_SHORT%" GEQ "40" (set BINARY_SOURCE_USER=Mx7f)
  - appveyor DownloadFile https://github.com/%BINARY_SOURCE_USER%/llvm-package-windows/releases/download/clang-%LLVM_VERSION%-nvptx/llvm-%LLVM_VERSION%-windows-amd64-msvc%VS_MAJOR_VERSION%-msvcrt.7z
  - 7z x llvm-%LLVM_VERSION%-windows-amd64-msvc%VS_MAJOR_VERSION%-msvcrt.7z
  - set LLVM_DIR=%CD%\llvm-%LLVM_VERSION%-windows-amd64-msvc%VS_MAJOR_VERSION%-msvcrt
  - set CLANG_RESOURCE_DIRECTORY=%LLVM_DIR%\lib\clang\%LLVM_VERSION%

  - set CMAKE_PREFIX_PATH=%LLVM_DIR%

  - if /I "%USE_CUDA%" EQU "1" (appveyor DownloadFile https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers2/cuda_9.2.148_windows -FileName cuda.exe)
  - if /I "%USE_CUDA%" EQU "1" (.\cuda -s nvcc_9.2 cudart_9.2)
  - if /I "%USE_CUDA%" EQU "1" (set CUDA_DIR=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2)

  - set ATOMLANG_DIR=%CD%

  - ps: git describe --tags | ForEach-Object { $_ -replace "release-", "" } | Set-Content atomlang_version.txt
  - set /p ATOMLANG_VERSION=<atomlang_version.txt

build_script:
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=%CD%\..\install -DCMAKE_GENERATOR_PLATFORM=x64
  - cmake --build . --target INSTALL --config Release
  - cd ..

  - set ATOMLANG_SHARE_PATH=%ATOMLANG_DIR%\install\share\atomlang
  - ps: |
        If($Env:LLVM_VERSION_SHORT -eq 60) {
          $Env:RELEASE_NAME = "atomlang-Windows-x86_64-$(git rev-parse --short HEAD)"
          Rename-Item install "$Env:RELEASE_NAME"
          7z a "$Env:RELEASE_NAME.zip" "$Env:RELEASE_NAME"
          Rename-Item "$Env:RELEASE_NAME" install
        }

test_script:
  - cd tests
  - ..\install\bin\atomlang run
  - cd ..

artifacts:
  - path: 'atomlang-*.zip'
    name: atomlang_release
