name: CI
on: [push, pull_request]

jobs:
  check_format:
    name: Check Format
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        env:
          CHECK_CLANG_FORMAT: 1
  build:
    name: Build (${{ matrix.os }}, llvm-${{ matrix.llvm }}, cmake=${{ matrix.cmake }}, cuda=${{ matrix.cuda }}, static=${{ matrix.static }}, slib=${{ matrix.slib }}, ${{ matrix.lua }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-16.04', 'ubuntu-18.04', 'macos-10.15']
        llvm: ['3.8', '5.0', '6.0', '7', '8', '9', '10', '11', '12']
        cmake: ['0', '1']
        cuda: ['0', '1']
        static: ['0', '1']
        slib: ['0', '1']
        lua: ['luajit', 'moonjit']
        exclude:

          - os: 'ubuntu-16.04'
            llvm: '5.0'
          - os: 'ubuntu-16.04'
            llvm: '6.0'
          - os: 'ubuntu-16.04'
            llvm: '7'
          - os: 'ubuntu-16.04'
            llvm: '8'
          - os: 'ubuntu-16.04'
            llvm: '9'
          - os: 'ubuntu-16.04'
            llvm: '10'
          - os: 'ubuntu-16.04'
            llvm: '11'
          - os: 'ubuntu-16.04'
            llvm: '12'
          - os: 'ubuntu-18.04'
            llvm: '3.8'

          - os: 'macos-10.15'
            llvm: '5.0'
          - os: 'macos-10.15'
            llvm: '8'
            cmake: '0'
          - os: 'macos-10.15'
            llvm: '9'
            cmake: '0'
          - os: 'macos-10.15'
            llvm: '10'
            cmake: '0'
          - os: 'macos-10.15'
            llvm: '11'
            cmake: '0'
          - os: 'macos-10.15'
            llvm: '12'
            cmake: '0'
          - os: 'macos-10.15'
            cuda: '1'
          - os: 'macos-10.15'
            static: '0'
          - os: 'macos-10.15'
            slib: '0'

          - os: 'macos-10.15'
            llvm: '10'

          - llvm: '5.0'
            cmake: '0'
          - llvm: '7'
            cmake: '0'

          - cmake: '0'
            static: '0'
          - cmake: '0'
            slib: '0'
          - static: '0'
            slib: '1'

          - static: '0'
            lua: 'luajit'

          - cmake: '0'
            lua: 'moonjit'

          - llvm: '3.8'
            cuda: '1'
          - llvm: '5.0'
            cuda: '1'
          - llvm: '6.0'
            cuda: '1'
          - llvm: '7'
            cuda: '1'
          - llvm: '8'
            cuda: '1'
          - llvm: '10'
            cuda: '1'
          - llvm: '11'
            cuda: '1'
          - llvm: '12'
            cuda: '1'

          - llvm: '3.8'
            static: '0'
          - llvm: '5.0'
            static: '0'
          - llvm: '6.0'
            static: '0'
          - llvm: '7'
            static: '0'
          - llvm: '9'
            static: '0'
          - llvm: '10'
            static: '0'
          - llvm: '11'
            static: '0'
          - llvm: '12'
            static: '0'

          - llvm: '3.8'
            slib: '0'
          - llvm: '5.0'
            slib: '0'
          - llvm: '6.0'
            slib: '0'
          - llvm: '7'
            slib: '0'
          - llvm: '8'
            slib: '0'
          - llvm: '10'
            slib: '0'
          - llvm: '11'
            slib: '0'
          - llvm: '12'
            slib: '0'

          - llvm: '3.8'
            lua: 'moonjit'
          - llvm: '5.0'
            lua: 'moonjit'
          - llvm: '6.0'
            lua: 'moonjit'
          - llvm: '7'
            lua: 'moonjit'
          - llvm: '8'
            lua: 'moonjit'
          - llvm: '10'
            lua: 'moonjit'
          - llvm: '11'
            lua: 'moonjit'
          - llvm: '12'
            lua: 'moonjit'
    steps:
      - uses: actions/checkout@v1
        env:
          LLVM_CONFIG: llvm-config-${{ matrix.llvm }}
          CLANG: clang-${{ matrix.llvm }}
          USE_CMAKE: ${{ matrix.cmake }}
          USE_CUDA: ${{ matrix.cuda }}
          STATIC_LLVM: ${{ matrix.static }}
          STATIC_LUAJIT: ${{ matrix.static }}
          SLIB_INCLUDE_LLVM: ${{ matrix.slib }}
          SLIB_INCLUDE_LUAJIT: ${{ matrix.slib }}
          ATOMLANG_LUA: ${{ matrix.lua }}
      - uses: actions/upload-artifact@v2
        with:
          name: atomlang-${{ matrix.os }}-llvm-${{ matrix.llvm }}
          path: |
            *.zip
